### ISSUE TITLE
`main.zig` example is old

### ISSUE THREAD

**Issue by alichraghi** [nektro/zig-pek#2]

**Comment by nektro** [comment]
in what way? does it no longer compile?

**Comment by alichraghi** [comment]
in `main.zig`, `compile` function arguments are different with `lib.zig`
https://github.com/nektro/zig-pek/blob/96945468b693684b72b68a9135a51ca993a284ad/src/main.zig#L49 https://github.com/nektro/zig-pek/blob/96945468b693684b72b68a9135a51ca993a284ad/src/lib.zig#L23

```diff
+ (comptime type, std.mem.Allocator, anytype, comptime astgen.Value, anytype)
- (writer: anytype, comptime value: astgen.Value, data: anytype)
```

not changed since [this commit](https://github.com/nektro/zig-pek/commit/e138d32d1a042dff857a6d3a73ec058051b463d5)

**Comment by nektro** [comment]
ah, thanks

**Comment by jblumie** [comment]
How is it supposed to look like? I'm trying to understand it but I can't (I'm new to zig)
